# Explore data loading from ALERCE/TAP

In [5]:
from pathlib import Path
ROOT = Path.cwd().parents[0]

In [4]:
import pandas as pd

In [3]:
import pyvo

# https://science.alerce.online/services/accessing-data-tap/
tap = pyvo.dal.TAPService("https://tap.alerce.online/tap")

query = """
SELECT TOP 100 *
FROM ztf.object
"""

job = tap.search(query)
df_objects = job.to_table().to_pandas()

df_objects.head()

,oid,ndethist,ncovhist,mjdstarthist,mjdendhist,corrected,stellar,ndet,g_r_max,g_r_max_corr,...,meanra,meandec,sigmara,sigmadec,deltajd,firstmjd,lastmjd,step_id_corr,diffpos,reference_change
0,ZTF21abghwbb,1,2304,59379.325868,59379.325868,False,False,1,NaN,NaN,...,269.537378,54.055274,NaN,NaN,0.0,59379.325868,59379.325868,correction_0.0.1,True,False
1,ZTF21abghwbg,2,2124,58953.448218,59379.325868,False,False,1,NaN,NaN,...,270.263325,54.010945,NaN,NaN,0.0,59379.325868,59379.325868,correction_0.0.1,True,False
2,ZTF21abghwcm,1,2299,59379.325868,59379.325868,False,False,1,NaN,NaN,...,270.869576,53.892974,NaN,NaN,0.0,59379.325868,59379.325868,correction_0.0.1,True,False
3,ZTF21abghwbj,1,1913,59379.326806,59379.326806,True,False,1,NaN,NaN,...,286.861523,67.678682,NaN,NaN,0.0,59379.326806,59379.326806,correction_0.0.1,True,False
4,ZTF21abghwca,1,2286,59379.325868,59379.325868,False,False,1,NaN,NaN,...,272.108703,58.094034,NaN,NaN,0.0,59379.325868,59379.325868,correction_0.0.1,True,False

In [45]:
df_objects[df_objects.ndet > 1]

,oid,ndethist,ncovhist,mjdstarthist,mjdendhist,corrected,stellar,ndet,g_r_max,g_r_max_corr,...,meanra,meandec,sigmara,sigmadec,deltajd,firstmjd,lastmjd,step_id_corr,diffpos,reference_change
52,ZTF20aayrfxa,4,1175,58976.500000,59805.250000,True,False,2,NaN,NaN,...,278.799203,-18.388217,0.000002,0.000157,425.917743,59379.314352,59805.232095,dev,False,False
54,ZTF21abghvyj,11,2199,58913.531701,59428.241609,False,False,2,NaN,NaN,...,274.203316,61.237618,0.000057,0.000076,48.915266,59379.326343,59428.241609,correction_1.0.6,True,False
60,ZTF18abpkmel,6,1082,58315.261713,59474.147442,True,True,3,NaN,NaN,...,279.495932,-18.706326,0.000039,0.000071,94.833090,59379.314352,59474.147442,correction_1.0.6,False,False
62,ZTF18abpkljg,7,1089,58315.262176,59484.172813,True,True,3,NaN,NaN,...,279.510695,-18.651188,0.000126,0.000049,104.858461,59379.314352,59484.172813,correction_1.0.6,False,False
64,ZTF18abpfoza,12,1568,58293.292917,60868.217292,True,False,5,NaN,NaN,...,279.330481,-18.760820,0.030700,0.029069,1488.902940,59379.314352,60868.217292,27.5.6,False,False
65,ZTF21abghwgb,6,1590,58314.253646,60872.304421,True,False,3,NaN,NaN,...,279.294695,-18.629295,0.039603,0.037528,1492.990069,59379.314352,60872.304421,27.5.6,False,False
71,ZTF18aamkcnq,313,2350,58229.425903,59379.329699,False,False,11,0.298901,NaN,...,275.818749,49.963242,0.000195,0.000181,29.981146,59349.348553,59379.329699,correction_0.0.1,False,False

In [ ]:
batch = df_objects["oid"].iloc[50:60].to_list()
objects_sql = ", ".join(f"'{oid}'" for oid in batch)

query = f"""
SELECT *
FROM ztf.detection
WHERE oid IN ({objects_sql})
ORDER BY oid, mjd, candid
"""

job = tap.search(query)
df_detections = job.to_table().to_pandas()

df_detections.head()

,candid,oid,mjd,fid,pid,diffmaglim,isdiffpos,nid,ra,dec,...,sigmagapbig,rfid,magpsf_corr,sigmapsf_corr,sigmapsf_corr_ext,corrected,dubious,parent_candid,has_stamp,step_id_corr
0,1625314351915010125,ZTF18abhcdba,59379.314352,1,1625314351915,20.454035,-1,1625,279.944550,-18.487811,...,0.1435,333120119,15.186162,100.0,0.007858,True,False,<NA>,True,correction_0.0.1
1,1625314351815010102,ZTF20aayrfxa,59379.314352,1,1625314351815,20.458471,-1,1625,278.799202,-18.388106,...,0.0315,333120118,13.073362,100.0,0.004819,True,False,<NA>,True,correction_0.0.1
2,2051232091815010110,ZTF20aayrfxa,59805.232095,1,2051232091815,19.956644,-1,2051,278.799205,-18.388328,...,0.0433,333120118,13.078772,100.0,0.007073,True,False,<NA>,True,dev
3,1625326342115015039,ZTF21abghvyj,59379.326343,1,1625326342115,20.695633,1,1625,274.203356,61.237672,...,0.3948,826120121,NaN,NaN,NaN,False,False,<NA>,True,correction_0.0.1
4,1674241602115015050,ZTF21abghvyj,59428.241609,1,1674241602115,20.700375,1,1674,274.203276,61.237564,...,0.6143,826120121,NaN,NaN,NaN,False,False,<NA>,True,correction_1.0.6

In [ ]:
objects_sql = ", ".join(f"'{oid}'" for oid in batch)

query = f"""
SELECT *
FROM ztf.probability
WHERE oid IN ({objects_sql})
ORDER BY oid
"""

job = tap.search(query)
df_detections = job.to_table().to_pandas()

df_detections.head()

,oid,class_name,classifier_name,classifier_version,probability,ranking
0,ZTF18abhcdba,AGN,stamp_classifier,stamp_classifier_1.0.4,0.122493,3
1,ZTF18abhcdba,asteroid,stamp_classifier,stamp_classifier_1.0.4,0.032100,5
2,ZTF18abhcdba,bogus,stamp_classifier,stamp_classifier_1.0.4,0.183461,2
3,ZTF18abhcdba,SN,stamp_classifier,stamp_classifier_1.0.4,0.044140,4
4,ZTF18abhcdba,VS,stamp_classifier,stamp_classifier_1.0.4,0.617807,1