# Validate downloads are complete

In [9]:
from pathlib import Path
import pandas as pd
ROOT = Path.cwd().parents[0]
DF_RAW = ROOT / 'data' / 'raw'

In [2]:
df_objects = pd.read_parquet(DF_RAW/'objects.parquet')
print(df_objects.shape)
df_objects.head()

(20000, 30)

,oid,ndethist,ncovhist,mjdstarthist,mjdendhist,corrected,stellar,ndet,g_r_max,g_r_max.mask,...,sigmadec,sigmadec.mask,deltajd,firstmjd,lastmjd,step_id_corr,diffpos,diffpos.mask,reference_change,reference_change.mask
0,ZTF17aaaaaak,4,1899,58096.133762,61229.482338,True,False,1,NaN,True,...,0.085000,False,0.000000,61229.482338,61229.482338,27.5.7a32.dev1,True,False,False,False
1,ZTF17aaaaaal,475,2186,58096.133762,61254.486435,True,False,284,NaN,True,...,0.004750,False,2889.011401,58365.475035,61254.486435,27.5.7a32.dev1,False,False,True,False
2,ZTF17aaaaaam,424,2011,58094.104572,60966.401991,True,False,182,NaN,True,...,0.005993,False,2524.951690,58441.450301,60966.401991,27.5.6,False,False,True,False
3,ZTF17aaaaaan,863,2261,58091.266956,61256.488137,True,False,588,NaN,True,...,0.002997,False,2913.041516,58343.446620,61256.488137,27.5.7a32.dev1,True,False,True,False
4,ZTF17aaaaaao,752,2262,58091.266956,61254.488009,True,False,428,NaN,True,...,0.003443,False,2913.994618,58340.493391,61254.488009,27.5.7a32.dev1,False,False,True,False

In [3]:
df_detections_01 = pd.read_parquet(DF_RAW/'detection'/'detections_0001.parquet')
print(df_detections_01.shape)
df_detections_01.head()

(266935, 36)

,candid,oid,mjd,fid,pid,diffmaglim,isdiffpos,nid,ra,dec,...,sigmapsf_corr,sigmapsf_corr.mask,sigmapsf_corr_ext,sigmapsf_corr_ext.mask,corrected,dubious,parent_candid,parent_candid.mask,has_stamp,step_id_corr
0,780139024415010003,ZTF17aaaaaas,58534.139028,1,780139024415,19.286362,-1,780,68.578037,49.087102,...,0.085275,False,0.088826,False,True,False,805139274415015015,False,False,bulk_1.0.0
1,996451014415015006,ZTF17aaaaaas,58750.451019,1,996451014415,20.461601,1,996,68.578156,49.087025,...,0.014409,False,0.019408,False,True,False,1012449364415015008,False,False,bulk_1.0.0
2,1122203914415020005,ZTF17aaaaaas,58876.203912,1,1122203914415,20.827101,-1,1122,68.578022,49.087117,...,0.037121,False,0.043674,False,True,False,1142204954415015008,False,False,bulk_1.0.0
3,993493532215010009,ZTF17aaaaaaw,58747.493530,1,993493532215,19.908823,-1,993,62.784025,46.340743,...,0.008953,False,0.018962,False,True,False,1009487112215010011,False,False,bulk_1.0.0
4,620487892715015024,ZTF17aaaaabd,58374.487893,2,620487892715,20.530899,1,620,71.898601,46.312892,...,100.000000,False,0.008753,False,True,False,631506042715010002,False,False,bulk_1.0.0

In [4]:
df_probabilities_01 = pd.read_parquet(DF_RAW/'probability'/'probabilities_0002.parquet')
print(df_probabilities_01.shape)
df_probabilities_01.head()

(63742, 6)

,oid,class_name,classifier_name,classifier_version,probability,ranking
0,ZTF17aaaaght,AGN,lc_classifier,hierarchical_rf_1.1.0,0.000224,14
1,ZTF17aaaaght,Blazar,lc_classifier,hierarchical_rf_1.1.0,0.000448,13
2,ZTF17aaaaght,CV/Nova,lc_classifier,hierarchical_rf_1.1.0,0.017080,6
3,ZTF17aaaaght,QSO,lc_classifier,hierarchical_rf_1.1.0,0.000056,15
4,ZTF17aaaaght,CEP,lc_classifier,hierarchical_rf_1.1.0,0.185472,2

In [26]:
files = sorted(Path(ROOT/'data'/'interim'/'probability').glob("*.parquet"))
unique_class = set()
for file in files:
    tmp = pd.read_parquet(file, columns=['class_name'])
    unique_class.update(tmp['class_name'])

In [27]:
unique_class

{'AGN',
 'Blazar',
 'CEP',
 'CV/Nova',
 'DSCT',
 'E',
 'EA',
 'EB/EW',
 'LPV',
 'Microlensing',
 'Periodic',
 'Periodic-Other',
 'QSO',
 'RRL',
 'RRLab',
 'RRLc',
 'RSCVn',
 'SESN',
 'SLSN',
 'SN',
 'SNII',
 'SNIIb',
 'SNIIn',
 'SNIa',
 'SNIbc',
 'Stochastic',
 'TDE',
 'Transient',
 'VS',
 'YSO',
 'asteroid',
 'bogus',
 'satellite'}